version: "3.8"

services:
  api:
    build:
      context: backend/
    ports:
      - 8000:8000
    volumes:
    - ./backend:/app
    command: sh -c "uvicorn fastapi_app:app --host 0.0.0.0 --port 8000"
    networks:
      - app
    container_name: api

  ui:
    build:
      context: frontend/
    ports:
      - 8501:8501
    depends_on:
      - api
    volumes:
      - ./frontend:/app
    networks:
      - app
    container_name: ui

networks:
  app:
    driver: bridge